spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    banner-mode: off
  datasource:
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
